---

version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(levelname)s - %(message)s"

    message:
        format: "%(message)s"

handlers:
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: sku_resend_null_inventory.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8


loggers:
    main_module:
        level: INFO
        handlers: [info_file_handler]
        propagate: no

root:
    level: DEBUG
    handlers: [info_file_handler]
